# Generated by Django 5.2 on 2025-05-07 02:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pessoa',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nome', models.CharField(max_length=100)),
                ('data_nascimento', models.DateField()),
                ('sexo', models.CharField(max_length=1)),
                ('cpf', models.CharField(max_length=11)),
                ('peso', models.FloatField()),
                ('altura', models.FloatField()),
            ],
        ),
    ]
