# Generated by Django 5.2 on 2025-05-07 02:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_alter_pessoa_data_nascimento'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pessoa',
            name='altura',
            field=models.FloatField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='pessoa',
            name='peso',
            field=models.FloatField(default=None, null=True),
        ),
    ]
